[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# The IR pipeline is essential for solving stack issues

via_ir = true

# The optimizer MUST be enabled for via_ir to work effectively
optimizer = true
optimizer_runs = 200

# [profile.default.zksync]
# compile = true

[etherscan]



#[profile.solx]
